# Generated by Django 4.1.6 on 2023-02-06 05:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('key', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(max_length=100, null=True)),
                ('temperature', models.FloatField(null=True)),
                ('symbol', models.CharField(max_length=10, null=True)),
                ('description', models.CharField(max_length=50, null=True)),
                ('feels_like', models.FloatField(null=True)),
            ],
        ),
    ]
